apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/1 * * * *" #1分ごと
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  suspend: false #一時停止した時にtrue
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: sleep-container
            image: centos:6
            command:
            - "sh"
            - "-c"
            args:
            # 約50%の確率で成功するコマンド
            - "sleep 40; date +'%N' | cut -c 9 | egrep '[1|3|5|7|9]'"
          restartPolicy: Never

# CronJobとJobの関係は、DeploymentとReplicaSetの関係に似ている（CronJobがJobを管理し、JobがPodを管理する）
# dateは、+でフォーマット指定。cut -c 9で９文字目を切り出す。egrepはファイル内の文字検索で正規表現が使える