apiVersion: apps/v1
kind: ReplicaSet #同一Podを複数生成・管理するためのリソース
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3 #複製するPod数
  selector:
    matchLabels:
      app: echo
  template: #template以下はPodリソースにおける定義と同じもの
    metadata:
      labels:
        app: echo #Pod名は重複しないように、後ろにランダムな識別子が付く
    spec:
      containers:
        - name: nginx
          image: gihyodocker/nginx:latest
          env:
            - name: BACKEND_HOST
              value: localhost:8080
          ports:
            - containerPort: 80
        - name: echo
          image: gihyodocker/echo:latest
          ports:
            - containerPort: 8080
