apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  completions: 1 #成功回数
  parallelism: 1 #Jobの並列数
  backoffLimit: 10 #失敗を許容する回数
  template:
    spec:
      containers:
      - name: sleep-container
        image: centos:6
        command: ["sh", "-c"]
        args: ["$(sleep 3600)"]
      restartPolicy: OnFailure

# ReplicaSetとの大きな違いは、起動するPodが停止することが予定されているかどうか
# ユースケース　バッチ処理（例えば、S3などへのアップロード）

# restartPolicy　Pod障害時に、Neverなら新規のPod, OnFailureなら再度同一のPodが利用される

# ku exec -it [job name] -- sh -c 'kill -9 `pgrep sleep`'(9は強制終了、pgrepはプロセスID出力)

# parallelismを指定し、completionsを指定しなかった場合、コンテナを起動しては特定のタスクを実行し続けるワークキューとして動作する